[tool.poetry]
name = "gflick"
version = "0.1.0"
description = ""
authors = ["Bùi Thành Nhân <hi@imnhan.com>"]
license = "MIT"

[tool.poetry.scripts]
gflick-google = "gflick:google"
gflick = "gflick:server"

[tool.poetry.dependencies]
python = "^3.7"
curio = "^1.2"
h11 = "^0.9.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
